# Generated by Django 3.2.5 on 2022-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_auto_20220215_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='id_type',
            field=models.CharField(choices=[('uida', 'uida'), ('pan', 'pan'), ('voter_id', 'voter_id'), ('covid', 'covid')], max_length=200, null=True),
        ),
    ]
