# Generated by Django 3.2.5 on 2022-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_alter_identy_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
