# Generated by Django 3.2.5 on 2022-02-23 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0032_remove_identy_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='django_username',
            field=models.OneToOneField(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
