# Generated by Django 3.2.5 on 2022-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_alter_person_django_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
