# Generated by Django 3.2.5 on 2022-02-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_alter_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
