# Generated by Django 3.2.5 on 2022-02-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0037_alter_identy_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
