# Generated by Django 3.2.5 on 2022-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0038_alter_identy_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='identy',
            name='idcard',
            field=models.FileField(default='default.jpg', upload_to='id/'),
        ),
    ]
