# Generated by Django 3.2.5 on 2022-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0044_alter_jharsewa_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='document',
            field=models.FileField(upload_to='jharsewa/% Y/% m/% d/'),
        ),
    ]
