# Generated by Django 3.2.5 on 2022-02-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0045_alter_jharsewa_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jharsewa',
            name='document',
            field=models.FileField(default='default.jpg', upload_to='jhar/'),
        ),
    ]
