# Generated by Django 3.2.5 on 2022-02-27 09:19

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0047_auto_20220226_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='idcard',
            field=models.FileField(upload_to=person.models.user_directory_path),
        ),
    ]
