# Generated by Django 3.2.5 on 2022-02-27 10:57

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0049_alter_identy_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='idcard',
            field=models.FileField(blank=True, null=True, upload_to=person.models.user_directory_path),
        ),
    ]
