# Generated by Django 3.2.5 on 2022-02-27 11:26

from django.db import migrations, models
import django.utils.timezone
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0050_alter_identy_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='idcard',
            field=models.FileField(blank=True, default=django.utils.timezone.now, upload_to=person.models.user_directory_path),
            preserve_default=False,
        ),
    ]
